### ISSUE TITLE
Exercicis de SQL i Àlgebra Relacional.sql

### ISSUE THREAD

**Issue by dumitrux** [dumitrux/BD-FIB#1]
Dentro de Exercicis de SQL i Àlgebra Relacional (L5), el Q5 no pasa un juego de pruebas y el Q1 varios.

**Comment by mpl1018** [comment]
solución del último ej (pasando todos los juegos de pruebas):
insert into cost_ciutat
(select distinct d.ciutat_dpt,0
from departaments d
where d.ciutat_dpt NOT in (
	select d1.ciutat_dpt
	from empleats e, departaments d1
	where d1.num_dpt=e.num_dpt 
	)
);
